### ISSUE TITLE
Register callback for specific response status code

### ISSUE THREAD

**Issue by reinert** [reinert/requestor#28]
Add the #on(int, AlwaysCallback) to the GDeferred's RequestPromise, enabling one to register a callback to be triggered only if a response with the informed status code is received.

The int should be three, two or one digit. When two or one digit, it embrace all other supressed digits.

**Comment by heat** [comment]
Hi. I suggest you to create a Enum that embrace these codes. Even the most generic.

The two digit maybe isn't a subclass of codes like the hundred digit. So it's wrong to capture that class.

```java
enum StatusCode {
  Informational(1xx)
  Continue(100)
  Sucess(2xx)
  ...
}
```

**Comment by reinert** [comment]
Nice suggestion. Actually, there's already a series of constants binding to each status code. See the [Response](https://github.com/reinert/requestor/blob/master/requestor/core/requestor-api/src/main/java/io/reinert/requestor/Response.java) class.

In order to avoid additional complexity on the method signature, I think it's better to stick with int as the first parameter and just wrap the constants in a new inner interface inside Response called StatusCode (Response.StatusCode) to be more legible.

Also, I think it's valid to create another interface to hold only the family codes (say Response.StatusFamily): 1 Informational, 2 Success, 3 Redirection, 4 Client Error and 5 Server Error.

As for the two digit inputs, although it's not a pattern, resolving such situations wouldn't be harmful and adds versatility to the API.

**Comment by reinert** [comment]
Idea implemented: https://github.com/reinert/requestor/commit/27d546a63161450808640b124c8e8754799e1b54

**Comment by reinert** [comment]
Actually, I will go with the enum idea, but a little bit different. I opened an issue about it: #37.

**Comment by heat** [comment]
I really like that.

Using play, I'm using status code in a new way that I liked.

```java
import static play.mvc.static.Http.*;
//static import gives access to all attrib

public class Work {
...
    public void test() {
     OK;
    TEMPORARY_REDIRECT;     
    }
...
}
```
