### ISSUE TITLE
[BREAKING CHANGE] (Re-)Rename RequestSender to RequestInvoker

### ISSUE THREAD

**Issue by reinert** [reinert/requestor#35]
Hi everyone, I'm considering renaming `RequestSender` back to `RequestInvoker` based on jax-rs 2.0 API terminologies.

Also, I want to come up with a better name to `HasHttpSendMethods`. Maybe `IsInvokable` (it sounds weird)? Or let it be called `RequestInvoker` and rename this former to `RequestInvocationBuilder`?

If someone is already using the API for real, than let me know so I can abort this change.

Thanks.

**Comment by heat** [comment]
:+1:
