### ISSUE TITLE
ResponseStatus interface

### ISSUE THREAD

**Issue by reinert** [reinert/requestor#37]
Create the ResponseStatus interface with getCode, getReasonPhrase and getFamily.

Also create an underlying enum with all status codes implemented, and an additional enum for family.

**Comment by heat** [comment]
How the users will  translate the getReasonPhrase, maybe it isn't a useful feature.

**Comment by reinert** [comment]
https://github.com/reinert/requestor/commit/e0be5bb120435aa854efecc58198e8183570ca71
