### ISSUE TITLE
No Boundary specified in multipart/form-data Header

### ISSUE THREAD

**Issue by smallporgies** [reinert/requestor#38]
So I'm trying to upload a file, with code that looks something like this:

    GWT.<Requestor>create(Requestor.class)
      .req("http://myAddress.com/blah")
      .accept("application/json")
      .payload(FormData.wrap(FormElement.as(formPanel.getElement())))
      .header("header1", "blah")
      .header("header2", "blah")
      .post();

and constantly getting a 400 back from the server (I'm using a jersey backend). I can't for the life of me see what's wrong with the request, except that the request payload looks something like this:

    ------WebKitFormBoundaryGGBY0sGSP04l0ASX
    Content-Disposition: form-data; name="file"; filename="ExampleUpload.xlsx"
    Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    
    
    ------WebKitFormBoundaryGGBY0sGSP04l0ASX--

Requestor sets the Content-Type request header to
`multipart/form-data`

whereas I suppose it should be
`multipart/form-data; boundary=----WebKitFormBoundaryGGBY0sGSP04l0ASX--`

Am I on to something here, or do you think I'm missing something else?

**Comment by reinert** [comment]
I guess it's a requestor error!

Requestor always set the Content-Type header to multipart/form-data when using the FormDataSerializerNative (which is the default).

I'm trying to fix it now!

**Comment by smallporgies** [comment]
Awesome! If there's anything you need from me let me know.

**Comment by reinert** [comment]
I just pushed https://github.com/reinert/requestor/commit/9ee4d4c257182ce048a73034f9a830624435fdeb to fix it.
Could you try the HEAD tree?

**Comment by reinert** [comment]
Just deployed to sonatype snapshot repository.

Add the following to your POM to get access to this repository:

```xml
<repositories>
    <repository>
        <id>oss-sonatype</id>
        <name>oss-sonatype</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

And change the version of requestor dependency to **0.3.0-SNAPSHOT**

**Comment by reinert** [comment]
I've tested some cases and they all passed.
Please let me know if it solved to you.
Thanks.

**Comment by reinert** [comment]
Just a quick tip...

I'm not sure if you shortened your piece of code to make it readable here, but don't always create a Requestor instance like in `GWT.<Requestor>create(Requestor.class)`. As [said in the docs](https://github.com/reinert/requestor/wiki/The-Requestor), it should be used as a singleton in your app.

**Comment by smallporgies** [comment]
Don't worry, I'm using it as a singleton, that was just for the example :)

And that SNAPSHOT works for me! Thanks very much for the quick turnaround!

**Comment by reinert** [comment]
Nice! Glad to help!
