### ISSUE TITLE
multipart/form-data content type being overridden

### ISSUE THREAD

**Issue by smallporgies** [reinert/requestor#40]
Using RequestorWithGwtJackson sets the default media type to application/json. This overrides the header set in the resolution to #38. Would you suggest creating a second Requestor instance in this case or do you think this can be handled more elegantly?

**Comment by reinert** [comment]
No. Requestor should only use the default media type if no media type was informed at all (in any of the processing phases). I'm fixing this issue right now!

**Comment by smallporgies** [comment]
Thanks :) Where this case is tricky is that of course for multipart/form-data media type the content-type should be left empty, so it is difficult for a filter to know that it shouldn't change it! I suppose in the case of a multipart form post there really is no other Content-Type that should be used so you could work it out from there...

**Comment by reinert** [comment]
The problem is that in the request processing, the processor wasn't doing nothing with the content-type header when the default FormDataSerializer identified was the Native one. But we must ensure the conten-type header is actually empty. So now I explicitly remove this header in the processing. It should work now. Check the latest snapshot.

**Comment by reinert** [comment]
If you're interested in the impl details, check my last commit https://github.com/reinert/requestor/commit/2cf8b69cb68dc1c345ec0ef06d843a0cd773cc83.

**Comment by reinert** [comment]
Actually, I redesigned the solution to be more extensible. Now the FormDataSerializer can return null values, meaning that the content-type header shouldn't be set. https://github.com/reinert/requestor/commit/1e9ac9071177448b47d00e908873bb4dfde8b837

**Comment by smallporgies** [comment]
Nice :)
I just need to reindex my repo mirror and then I should be able to test and confirm... thanks once again for the quick turn around!
