### ISSUE TITLE
Version 0.2.0 does not work

### ISSUE THREAD

**Issue by janblok** [reinert/requestor#51]
With GWT 2.7.0 I get:
[INFO]    Tracing compile failure path for type 'io.reinert.requestor.RequestDispatcherImpl'
[INFO]       [ERROR] Errors in 'jar:file:/C:/data/m3/repository/io/reinert/requestor/core/requestor-api/0.2.0/requestor-api-0.2.0.jar!/io/reinert/requestor/RequestDispatcherImpl.java'
[INFO]          [ERROR] Line 79: The constructor Request(XMLHttpRequest, int, RequestCallback) is not visible
[INFO]          [ERROR] Line 88: The method fireOnResponseReceived(RequestCallback) from the type Request is not visible

With GWT 2.6.1 I get something the same, only this time that Collections.emptyIterator() can not be found...which is correct since it's added in GWT 2.7.0

**Comment by reinert** [comment]
Hi @janblok. Requestor is currently compatible only with gwt 2.7.0. You may forgot to set requestor dependency order upfront gwt's. See this [important note](https://github.com/reinert/requestor/wiki/Getting-Started#add-the-required-dependencies-to-your-project) in Getting Started wiki page. If you use maven, just declare requestor dependency before gwt dependency. If you don't, put requestor dependency above gwt dependency in your classpath configuration.

**Comment by janblok** [comment]
Well it after spending 2 hours I understood the lib does override a core google class which requires the libs to be in front. As this is so an important note you might want to refer to the note from the home readme.
The bad thing is, it got it working with maven by indeed placing the libs in front, the bad thing is we can't control superdev compiler order, so in debug I'm still stuck with this. (read: the lib is not usable at all)

Might <super-source> be a way out for your trick? see: http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html

**Comment by reinert** [comment]
I see. I didn't had any issue neither was notified using SDM until now.
The showcase project works correctly using SDM, in case you want to check it out locally
I'll follow your tip and see if I can do something to ensure having no problems related to this override.

FYI, I have an [open patch](https://gwt-review.googlesource.com/#/c/12620/) to GWT to overcome this situation.

**Comment by janblok** [comment]
I was looking for voting on the patch :-) ... having these methods "protected" would help a lot indeed.

**Comment by reinert** [comment]
Definetly! I'll try setting my com.google.gwt.http.client.Request as super-source and give you an answer. Thanks for the suggestion!

**Comment by reinert** [comment]
@janblok I finally got to a pretty minimal and (most possible) elegant solution (workaround) to this problem. Instead of overriding the com.google.gwt.http.client.Request class, I managed to create a new one in the same package, inheriting from it and exposing the required members. No classpath tricks are needed anymore.

If you could compile master branch in your local machine and try again to see if the problem is gone, I'd really appreciate your feedback.

Thanks!
