### ISSUE TITLE
UriBuilder with template parameters Uncaught TypeError

### ISSUE THREAD

**Issue by natros** [reinert/requestor#53]
Using this example from documentation throws an exception

```java
UriBuilder.fromPath("server/{res}/{id}").build("resource", 1).toString();
```

```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
```

GWT 2.7.0
Requestor 0.2.0

**Comment by reinert** [comment]
Thanks for reporting. It's a bug in uri parsing. This bug is already fixed in version 0.3.0-SNAPSHOT.
You can try the snapshot, there are some people using it already. The docs can be a little outdated though. I'll be releasing 0.3.0 with updated docs in a month.

**Comment by natros** [comment]
It's not working with 0.3.0-SNAPSHOT which I believe is from 20150505153644.

**Comment by natros** [comment]
I built it locally and seems to work

**Comment by natros** [comment]
Hum! Not sure if this is the expected result.

`/server/%257Bres%257D/%257Bid%257D`

https://github.com/natros/requestor-demo/blob/master/src/main/java/pt/ipb/requestor/demo/client/Main.java

**Comment by reinert** [comment]
Definitely not. I'm cloning your demo to check the fault behavior. Thanks for reproducing it.

**Comment by reinert** [comment]
Please, pull latest commit locally, install requestor and check if the problem's still there.

**Comment by natros** [comment]
It's working.

Thank you.
