### ISSUE TITLE
Intercept a 401 and redirect

### ISSUE THREAD

**Issue by natros** [reinert/requestor#54]
Hi,

How can I intercept a 401 and redirect the user to a login page. 

I tried to register a ResponseInterceptor and ResponseFilter, but none of them is called after a 401 response from server.

**Comment by reinert** [comment]
Hi @natros 

Currently, filters and interceptors are only executed when the response is successful, but this is subject to change (your opinion is important).

The way you could achieve what you want, is creating a custom `DeferredFactory` in which you register a failCallback performing such logic in every created promise.

Showcase has as example of that:
* [`ShowcaseDeferredFactory`](https://github.com/reinert/requestor/blob/master/examples/requestor-showcase/src/main/java/io/reinert/requestor/examples/showcase/ShowcaseDeferredFactory.java): registers one alwaysCallback and one failCallback in every promise;
* [`Showcase.gwt.xml`](https://github.com/reinert/requestor/blob/master/examples/requestor-showcase/src/main/resources/io/reinert/requestor/examples/showcase/Showcase.gwt.xml#L47-50): the ShowcaseDeferredFactory is activated via deferred binding.

There's no documentation yet about this feature. But the above example is enough to get the essentials.

I suggest you try to make it work this way. I'd appreciate if you give a feedback about this feature, whether you find it too complicated or necessary. And about Filters and Interceptors, if they should be executed in every response (not only successful ones).

Thanks.

**Comment by reinert** [comment]
I just push a patch that includes unsuccessful responses (401 including) into response processing. So you should be able now to filter 401 responses and redirect.

Here's an example using A&P:
```java
        requestor.register(new ResponseFilter() {
            @Override
            public void filter(Request request, ResponseFilterContext response) {
                if (response.getStatusCode() == 401)
                    placeController.goTo(new HomePlace());
            }
        });
```
