### ISSUE TITLE
Modify strategy for exposing Promise API by implementations

### ISSUE THREAD

**Issue by reinert** [reinert/requestor#64]
Erase default promise API by making Promise interface as a marker interface only, and exclude default and removing Callback class.

Implementations should only replace this Promise marker interface by their own (usually just by declaring it as extending from their promise interface).

ps: move promise and deferred classes to root package

**Comment by heat** [comment]
You could keep your default Promise class and mark himself with new Interface.

**Comment by reinert** [comment]
Providing a default Promise API is a no-goal for Requestor. 
Instead, the project claims that one can integrate any promise library into it.
Besides, declaring default API will restrict a lot how others can integrate external promise APIs, making it even impossible to achieve it.
So a marker interface is the most clean, effortless and extensible solution for this problem.
