### ISSUE TITLE
Upgrade to GWT 2.8.2

### ISSUE THREAD

**Issue by Nirostar** [reinert/requestor#73]
Would it be possible to upgrade this useful library to be compatible with GWT 2.8.2?

Kind regard
Nirostar

**Comment by reinert** [comment]
Hi Nirostar. Unfortunately I don't touch this project for a long time, not even in gwt anymore. I have a pending patch (0.3.0) with many useful enhancements pending but I just can't get into it anymore. Feel free to fork or contribute. I appreciate your interest. I'm here to clarify any doubts you might have.

**Comment by reinert** [comment]
Hello @Nirostar. I just launched requestor v1. It works for any GWT2 version and we should impls for JVM/Android and J2CL soon.
